name=input("Enter patient Name:")
age=int(input("Enter patient Age:"))
gender=input("Enter patient Gender:")
blood_group=input("Enter patient Blood Group:")
weight=float(input("Enter patient Weight:"))
height=float(input("Enter patient Height:"))
consulation_fee=float(input("Enter Consultation Fee:"))
registration_charges=float(input("Enter Registration charges:"))
print("\n")
total_fee=consulation_fee+registration_charges
print("          RihanRK SPECIAL HOSPITAL ")
print("          Patient information card  ")
print("-"*50)
print(f"Patient Name         : {name}")
print(f"Patient Age          : {age}")     
print(f"Patient Gender       : {gender}")
print(f"Patient Blood Group  : {blood_group}")
print(f"Patient Weight       : {weight}")
print(f"Patient Height       : {height}")
print(f"Consultation Fee     : {consulation_fee}")
print(f"Registration Charges : {registration_charges}")
print("-"*50)
print(f"Total Fee            : {total_fee}")
print("\n")
print("Thank you for visiting. We wish you a speedy recovery!")
print("\n")